/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.17.0-alpha.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/server";
import type * as addMemory from "../addMemory";
import type * as getShortTerm from "../getShortTerm";
import type * as memories from "../memories";
import type * as reviseShortTerm from "../reviseShortTerm";
import type * as storeUser from "../storeUser";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: ApiFromModules<{
  addMemory: typeof addMemory;
  getShortTerm: typeof getShortTerm;
  memories: typeof memories;
  reviseShortTerm: typeof reviseShortTerm;
  storeUser: typeof storeUser;
}>;
