/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.6.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as addMemory from "../addMemory.js";
import type * as getShortTerm from "../getShortTerm.js";
import type * as memories from "../memories.js";
import type * as reviseShortTerm from "../reviseShortTerm.js";
import type * as storeUser from "../storeUser.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  addMemory: typeof addMemory;
  getShortTerm: typeof getShortTerm;
  memories: typeof memories;
  reviseShortTerm: typeof reviseShortTerm;
  storeUser: typeof storeUser;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
